[tools]
uv = "latest"

[tasks.ruff]
run = "uv run ruff check"

[tasks.ty]
run = "uv run ty check"

[tasks.test]
run = "uv run pytest"

[tasks.check]
depends = ["ruff", "ty", "test"]

[tasks.sniff-start]
run = "./scripts/sniff-start"

[tasks.sniff-stop]
run = "./scripts/sniff-stop"
